name = "estratosferica-tiktok-creators"
main = "src/index.js"
compatibility_date = "2026-08-04"

workers_dev = true

[vars]
TIKTOK_APP_REVIEW_STATUS = "rejected"
ENABLE_TIKTOK_DRAFT_TRANSFER = "false"
TIKTOK_SANDBOX_REVIEW_MODE = "false"
